### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by NicoHood** [martinling/libserialport#18]
Hi,
can you please tag releases for this software?

Is this also the official dev tree as the website does never point to github?
http://sigrok.org/wiki/Libserialport

**Comment by martinling** [comment]
Hi Nico,

This is just my personal copy of the repository, the official one is on sigrok.org and has the releases tagged:

http://sigrok.org/gitweb/?p=libserialport.git
git://sigrok.org/libserialport

This is mentioned on the web page and is also on the description for this repository.

I rarely look at issues posted on this repository, sorry for the slow response!

Martin
