### ISSUE TITLE
Add a note about building libserialport on Windows to README file

### ISSUE THREAD

**Issue by ymyasoedov** [martinling/libserialport#2]
Please, add a note, that make should be run with LDFLAGS=-no-undefined to be able to build shared library:
$ make LDFLAGS=-no-undefined

Otherwise, without LDFLAGS you will get:
$ make
  CC       serialport.lo
  CCLD     libserialport.la
libtool: link: warning: undefined symbols not allowed in i686-pc-cygwin shared libraries

**Comment by ElectricRCAircraftGuy** [comment]
Hi, can you help me build and use it in Windows please? See here: https://github.com/martinling/libserialport/issues/10
