### ISSUE TITLE
sp_nonblocking_write does sends the first byte only, whereas sp_blocking_write is working properly [under Windows]

### ISSUE THREAD

**Issue by tomay3000** [martinling/libserialport#20]
Hello,
Under **Windows XP SP3**, I have tried to use **sp_nonblocking_write** function to send AT command to a phone connected through usb, this function always returns 1 (sends only the first byte), whereas **sp_blocking_write** function works without problems.

What could be the problem ?

Thank you for your understanding.

**Comment by martinling** [comment]
The changes we discussed on #21 to improve this behaviour were merged in commit 39df7833, libserialport now uses an internal buffe, approx. 50ms of data at the current baud rate, for nonblocking writes on Windows.
