### ISSUE TITLE
Can't link statically on Windows (undefined reference to setupapi)

### ISSUE THREAD

**Issue by glebm** [martinling/libserialport#30]
When I try linking libserialport with `-static`, it complains about undefined references to some setupapi functions:

```
lib\libserialport.a(windows.o):(.text+0x615): undefined reference to `__imp_CM_Get_Parent'
... (about a dozen of these)
```

Tried adding `-lsetupapi` before/after `-static` but it didn't help.

libserialport installed via https://github.com/Alexpux/MINGW-packages/pull/4841

**Comment by martinling** [comment]
Hi @glebm,

I have just built and installed the `mingw-w64-libserialport-git` package from https://github.com/msys2/MINGW-packages/pull/4841 using the MSYS2 MinGW 64-bit shell.

Everything seems to install correctly, and running `pkg-config --libs libserialport --static` reports the correct linker flags for a static build:
```
-LC:/msys64/mingw64/lib -lserialport -lsetupapi
```

I can reproduce the undefined references by adding `-static` to the `CFLAGS` in libserialport's `examples/Makefile` and then trying to `make` the examples.

If I then add `--static` to the pkg-config arguments in that Makefile, the build succeeds.

This is all as I would expect.

I think when you ran into this you probably just had the ordering wrong. The order of `-l` arguments is important: the linker will process the inputs, including libraries, in the order that they appear on the command line. So `-lserialport -lsetupapi` will work, but `-lsetupapi -lserialport` will not.

The linker needs to see its inputs in the right order:

1. Your code, which will define `main` and other symbols, but will generate undefined references to symbols from libserialport.
2. The libserialport library, which will define the missing `sp_` symbols but - for static linking - will generate undefined references to setupapi symbols.
3. The setupapi library, which will provide the missing symbols needed.

If `-lsetupapi` is processed first, the linker will just see no need to include any symbols from it.
