### ISSUE TITLE
Loss of parity setting under Windows OS.

### ISSUE THREAD

**Issue by brickpool** [martinling/libserialport#36]
This problem only applies to Windows OS!

There are two parameters member of `dcb` structure that control the Parity settings: `fParity` and `Parity`. Windows OS should have a bug with the function `GetCommState`: `fParity` return always `FALSE`: (see https://stackoverflow.com/a/36650872/12342329).

Every call of `get_config` (file `serialport.c`) resets the parity setting of the config structure which have previously made.

```
static enum sp_return get_config(struct sp_port *port, struct port_data *data,
	struct sp_port_config *config)
{
...
#ifdef _WIN32
	if (!GetCommState(port->hdl, &data->dcb))
		RETURN_FAIL("GetCommState() failed");
...
	if (data->dcb.fParity)
		switch (data->dcb.Parity) {
...		
	}
	else
		config->parity = SP_PARITY_NONE;
...
```

https://github.com/martinling/libserialport/blob/d9cc984fe7acc487d39366a98f1d3759f6129361/serialport.c#L1692

https://github.com/martinling/libserialport/blob/d9cc984fe7acc487d39366a98f1d3759f6129361/serialport.c#L1708

https://github.com/martinling/libserialport/blob/d9cc984fe7acc487d39366a98f1d3759f6129361/serialport.c#L1729

**Comment by martinling** [comment]
Thanks for the heads up on this. Fixed in 42c7d87.
