### ISSUE TITLE
sp_wait issue under windows...

### ISSUE THREAD

**Issue by Matrix-Zhang** [martinling/libserialport#4]
Hi:

I'm useing your library with my serialport tool which the one of the goals is cross platform ...

there's an issue with sp_wait function and sp_nonblocking_read under windows os,

first, when the input buffer is nothing, the sp_wait will block until some data was recived in driver's buffer,

and then i use sp_nonblocking_read until it return 0 ( read all buffer)

the next loops for call sp_wait , it will not block anymore...

i check it out it because of the calling below in sp_nonblocking_read:

if(bytes_read > 0)
{
    if (WaitCommEvent(port->hdl, &port->events, &port->wait_ovl) == 0) {
		if (GetLastError() != ERROR_IO_PENDING) {
			sp_close(port);
			RETURN_FAIL("WaitCommEvent() failed");
		}
	}
}

i modify the line :if(bytes_read > 0) to if(bytes_read == 0)

it works better now, but not perfect....

at last, thanks a lot for your job, and sorry for my bad english...

**Comment by martinling** [comment]
Can you try with this change:

https://github.com/martinling/libserialport/commit/01284d267cdbe0286761b1cc76947e6016466e8a

**Comment by martinling** [comment]
I think this issue should be fixed in the current master branch now. Please reopen if you still have problems.
