### ISSUE TITLE
read opportunity on windows

### ISSUE THREAD

**Issue by Matrix-Zhang** [martinling/libserialport#5]
Hi:

i find when i writing data to serialport, and waiting at once, the waiting will block forever...

but after writing if i sleep 100ms or longer, it will be ok.

i'm not very good at serialport communication,  is it normal on windows?

thanks and best regards!

**Comment by martinling** [comment]
Can you try with this change:

https://github.com/martinling/libserialport/commit/01284d267cdbe0286761b1cc76947e6016466e8a

**Comment by martinling** [comment]
I think this issue should be fixed in the current master branch now. Please reopen if you still have problems.
